### PR TITLE
Log X-Cld-Error header in dev mode

### PR DESCRIPTION
**Pull request by ayan-joshi**
# Description

solving the following issue listed in next-cloudinary 

## Issue Ticket Number

Issue link : https://github.com/cloudinary-community/next-cloudinary/issues/512 

@colbyfayock

### CODE REVIEW

**Comment by colbyfayock** [comment]
thanks @ayan-joshi in addition to the comment, i think we need to update our return type as right now it's only set to be a boolean

https://github.com/cloudinary-community/cloudinary-util/blob/88f7e413072044be36b0a125049f5fb3bbc0625c/packages/util/src/lib/cloudinary.ts#L165

I would expecte we would want to create a new interface below the existing options interface, such as `PollForProcessingImageResponse` with the response types

**Comment by ayan-joshi** [comment]
okay I'll work on the comments @colbyfayock

**Comment by colbyfayock** [comment]
this looks good, thanks @ayan-joshi 

i'm going to merge this into a beta release that we can then integrate into the Next.js SDK to test before publishing it as a breaking change, just in case we need to make any further adjustments first

**Comment by colbyfayock** [comment]
@all-contributors please add @ayan-joshi for code

**Comment by colbyfayock** [comment]
@ayan-joshi this PR is eligible for free Cloudinary Hacktoberfest swag. Please send me an email to hacktoberfest@cloudinary.com with your name, GitHub username, and a link to this PR where I'll send you further instructions. Happy Hacktoberfest!

**Comment by ayan-joshi** [comment]
> @ayan-joshi this PR is eligible for free Cloudinary Hacktoberfest swag. Please send me an email to [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your name, GitHub username, and a link to this PR where I'll send you further instructions. Happy Hacktoberfest!

@colbyfayock Hey thats cool,  thanks I'll do the needful

**Pull request merged**
