### PR TITLE
Add cloudinaryAnalytics to Video Player types #171

### LINKED ISSUE #171: [Feature] Add cloudinaryAnalytics to Video Player types
## What?
https://cloudinary.com/documentation/video_player_api_reference#ads_and_analytics

## Where?
https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/types/src/types/cloudinary-video-player.ts

### PR DESCRIPTION
**Pull request by nooras**
# Description

Added cloudinaryAnalytics to Video Player types

## Issue Ticket Number

Fixes #171 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Fix or improve the documentation
- [ ] This change requires a documentation update

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/colbyfayock/cloudinary-util/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/cloudinary-util/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @nooras thanks for the PR - i think it would make sense to type out the custom data attribute, since it seems like that's a pre-defined set of 5 names, including customData, customData2, customData3, etc

**Comment by nooras** [comment]
> hey @nooras thanks for the PR - i think it would make sense to type out the custom data attribute, since it seems like that's a pre-defined set of 5 names, including customData, customData2, customData3, etc

Hey @colbyfayock 
Can you check it now the changes. 

Let me know if any changes are required.

**Comment by colbyfayock** [comment]
the only thing is i think it's supposed to be a nested object. from the example in the docs formatted:

```
cloudinaryAnalytics: {
  **customData**: {
    customData1: "My-Product-Name",
    customData2: "My-Product-Description",
    customData3: "My-Product-Category",
    customData4: "My-Product-Alternative",
    customData5: "My-Product-SKU-123"
  }
}
```

**Comment by nooras** [comment]
@colbyfayock 
Thanks for the clarification :)
Can you confirm it once is below changes are correct ? Then i will push it
```
export interface CustomData {
  customData: CustomDataKeys;
}

export interface CustomDataKeys {
  customData1?: string;
  customData2?: string;
  customData3?: string;
  customData4?: string;
  customData5?: string;
}
```

**Comment by colbyfayock** [comment]
yup that appears good to me, though i would prefix the names. they'll come out long, but i personally think its good to namespace them, particularly with a lot of types that may have crossover

CloudinaryVideoPlayerOptionsCloudinaryAnalytics
CloudinaryVideoPlayerOptionsCloudinaryAnalyticsCustomData
CloudinaryVideoPlayerOptionsCloudinaryAnalyticsCustomDataKeys

**Comment by nooras** [comment]
> cloudinaryAnalytics

@colbyfayock 
Thanks for your suggestion. I have updated like the way you mentioned.
Do check the commit. Let me know if any changes needed

**Comment by colbyfayock** [comment]
thanks @nooras - this PR is eligible for Cloudinary Hacktoberfest swag! Please send me an email to hacktoberfest@cloudinary.com with your name, GitHub username, and a link to this PR where I'll send further instructions. Happy Hacktoberfest!

**Comment by colbyfayock** [comment]
@all-contributors please add @nooras for code

**Pull request merged**
